name: Pr build check

on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Report status
        if: ${{ success() }}
        run: echo "Build succeeded"